---
title: A two agents model of inequalities.
format: latex
---



## Preference for wealth and marginal propensity to consume

For now, we consider a single representative agent. She has the ability to buy a two periods bond, yielding 1 after one period. The price of the bond at any date is $q$, hence its (riskfree) interest rate is $r=1/q$.

Agent values consumption $c_t$ and wealth $b_t q_t$ so that she maximizes[^footnote]:

$$\max \sum_t \beta^t \left( \frac{c_t^{1-\frac{1}{\sigma}}}{1-\frac{1}{\sigma}}+ \varphi \frac{ (1+b_t)^{1-\frac{1}{\eta}} } {1-\frac{1}{\eta}} \right)$$

under the budget constraint

$$c_t = y_t + b_{t-1} - b_t q_t$$

where $y_t$ is exogenous income following AR1 

$$(y_t-\overline{y})=\rho (y_{t-1}-\overline{y}) + \epsilon^y_t$$

__1. Write down the optimality condition for debt holdings.__

*Response:*

$$q_t = \beta \left(\frac{c_{t+1}}{c_{t}}\right)^{-\frac{1}{\sigma}}+\varphi \left(\frac{1 + b_t q_t}{c_{t}}\right)^{-\frac{1}{\sigma}}$$


__2. What are the equations defining the deterministic equilibrium?__


*Response:*
$$q = \beta + \varphi \left(\frac{1 + b q}{c}\right)^{-\frac{1}{\sigma}}$$


__3. Inspect `one_agent.mod` model. Show that there is a unit root. Can you interpret it?__

*The `one_agent.mod` model is a standard consumption saving model without preference for wealth. 
Just add `check;` to see the unit root.
In this setup, any steady-state level of debt is feasible (in a deterministic model).*


__4. What is the consumption response to a temporary income shock? To a permanent one? (with autocorrelation $\rho=0.9$ and $\rho=1.0$)__

*Response:*

Change the income equation:

- for a temporary shock remove the zero to get: `y = ybar + e_y`
- For a persistent one, define a new parameter in the parameters line initialized to `rho=0.9` and change the equation to `y - ybar = rho*(y(-1) - ybar) + e_y`. In the case `rho=1.0` note the apparition of a second unit root.

In the simulations, pay attention to the magnitude of the shock `e_y` (1% by default) to compare it to the magnitude of the response for assets `b`.

__5. In the modfile, add a preference for wealth term in the utility function and adjust the calibration of `beta` accordingly.__
 
*Response*:

Parameters `phi` and `eta` are already predefined.

Add `+ phi*(1+b*q)^(-1/eta)/(c^(-1/sigma))` to the Euler equation and `beta = 1/r - phi*(1+bbar*q)^(-1/eta)/(cbar^(-1/sigma));` in the definition of parameters

Check the residuals (with command `resid;`) to ensure that everything is fine. Incidentally we can see that one unit root has disappeared, because pref. for wealth pins down equilibrium asset holdings.

Result is in the `one_agent_2.mod` file.

__6. Simulate the response to a temporary and a persistent shock. Given `phi` what is the effect of `eta`?__

*Response*:


Now the savings response to transitory shock is mean reverting, while the response to a persistent shock is persistent and even increasing over time.

`eta` affects the long run savings level in response to a temporary income shock. (If curious you should be able to check it does not depend on phi).

## A two agents model

We now assume there are two agents: bottom and top earners. Top earners amount for a fraction $\chi$ of the total population. Together they earn a fraction $z\in[0,1]$ of the total production $y$ which is an AR1 process as in the first part. The rest goes to the bottom earners.

Top earners can save by lending to bottom earners. We denote by $B_t$ the total quantity of riskfree bonds, traded at $q_t$. Note that debt per capita is $\frac{B_t}{\chi}$ for top earners and $\frac{B_t}{1-\chi}$ for bottom earners. Top earners have preference for wealth as in the first part, while bottom earners have standard preferences (with $\varphi=0$)

__1. Write down the budget equations for both agents. What are the new Euler equations? Check that it is consistent with the `two_agents.mod` modfile. What are the per capita variables?__

*Response*:

Budget constraints are included in the modfile.

Per capita variables: `c_t`, `c_b`, `b_t` and `b_b`.

__2. What is qualitatively the effect of a permanent redistributive shock? (simulate the model)__

*Response*:


With increased income, top earners want to increase their asset holdings. This will happen since bottom earners are indifferent in the steady-state. During the transition however, we see a decrease in the interest rate (to convince borrower to accept a decreasing path of consumption over time).


## Calibrating and simulating the model

The model in the modefile is pre-calibrated to match US data in 1983. Assume the model is in equilibrium for an initial level of debt $B=0.91$ (which is the debt/gdp ratio in the us in 1983). 

Taking $\varphi=0.05$ as constant, for any given choice of $\eta$, there is a unique value of $\beta$ consistent with the equilibrium as in the one agent case.

Now we would like to calibrate the value of $\eta$ so as to match the marginal propensity to save of top earners which was approximately 50% in 1983. 

Since the two agents model is already calibrated for most variables, we reuse it rather than adapting the one agent model.

__1. In the model `two_agents.mod` replace the Euler equation of bottom earner by `q = 1/rbar`. Justify why, from the top earners perspective, the model is now equivalent to a single agent model.__

*Response*:


Interest rate is the only manifestation of bottom earners preferences in the model. If we set it equal to a constant, top earners are now facing an infinitely elastic demand of bonds as in the one agent case.

__2. Use the modified model to compute the marginal propensity out of a permanent income shock after 6 periods. Choose parameter `eta` so that this m.p.s. is approximatively 50%.__

*Response*:


Several options here. We can just make a persistent shock of size sig_z to the overall income $y$ and compute the marginal propensity to save at different periods (variable mps). It must be normalized by the initial income level of top earners. We can then run computations for different values of $eta$ until we find the desired value.

Modified model is `two_agents_mps.mps`. I found eta=0.6 to be a good calibration.

__3. What is the effect of a 10% permanent increase in inequalities? Over 30 years and in the long run?__

*Response*:


We can set the value of eta that we found, increase the standard deviation of sig_z to 0.1 and change the simulation horizon (first to 30 then to 200).

Over 30 years I found an increase of 25 of the debt/gdp level (`B`). Over 200 years it amounts to 0.6/0.7.




[^footnote]: this is the "preference for wealth" specification