module one_agentSteadyState2
#
# NB: this file was automatically generated by Dynare
#     from one_agent.mod
#
export steady_state!

function steady_state!(ys_::Vector{<: Real}, exo_::Vector{<: Real}, params::Vector{<: Real})
@inbounds begin
    ys_[1]=params[10];
    ys_[3]=params[11];
    ys_[2]=params[12];
    ys_[4]=0.0;
    # Auxiliary equations
end
end
end
