function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=params(10);
    ys_(2)=params(9);
    ys_(7)=params(11);
    ys_(5)=ys_(7)/params(14);
    ys_(6)=(-ys_(7))/(1-params(14));
    ys_(3)=params(12);
    ys_(4)=params(13);
    ys_(9)=params(3);
    ys_(8)=1/ys_(9);
    ys_(10)=0.0;
    % Auxiliary equations
end
