---
title: "Small Open Economy Extension"
format:
    revealjs:
        navigation-mode: grid
        layout: wide
        toc: true
        toc-depth: 1
        toc-title: Plan
---


## Why a small open economy?


what are the classical reasons to open:
    - financial integration
      - smooth shock
    - trade integration

what is financial integration:
    complete financial market? what does it mean
    riskfree bond



## Empirical Facts

puzzles...


## Deterministic Small Open Economy


model setup


world interest rate

derive solution

trade balance: ${TB}_t=y_t-c_t$
current account: ${CA}_t = TB_t + r a_t$

assume $\beta(1+r) = 1$


Consumption level: 

$c_0 = ...permanent income$


-> intertemporal approach to the current account
    - procyclical trade balance

-> what is the steady-state?

## Stationarize the distribution

## Add back capital

-> simple but trivial investment dynamis

How to fix volatility of investment?

...

-> solution add adjustment costs

model pas super: un parametre un momen

## Add non tradables

countercyclical trade balance


# A quantitative SOE moel

 Schmitt
Grohe and Uribe JIE (2004) 

## Result:

Schmitt-Grohe & Uribe

# Conclusion

## Towards IRBC models

## What as small open economy problems?

DSGE...
puzzles