function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=params(10);
    ys_(3)=params(11);
    ys_(2)=params(12);
    % Auxiliary equations
end
