module modelStaticParamsDerivs
#
# NB: this file was automatically generated by Dynare
#     from model.mod
#
export params_derivs

function params_derivs(y, x, params)
@inbounds begin
end
rp = zeros(4, 14);
@inbounds begin
end
gp = zeros(4, 4, 14);
@inbounds begin
end
rpp = zeros(0,4);
@inbounds begin
end
gpp = zeros(0,5);
@inbounds begin
end
hp = zeros(0,5);
@inbounds begin
end
(rp, gp, rpp, gpp, hp)
end
end
