module two_agentsDynamicParamsDerivs
#
# NB: this file was automatically generated by Dynare
#     from two_agents.mod
#
export params_derivs

function params_derivs(y, x, paramssteady_state, it_, ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
end
rp = zeros(6, 15);
@inbounds begin
end
gp = zeros(6, 13, 15);
@inbounds begin
end
rpp = zeros(0,4);
@inbounds begin
end
gpp = zeros(0,5);
@inbounds begin
end
hp = zeros(0,5);
@inbounds begin
end
g3p = zeros(0,6);
@inbounds begin
end
(rp, gp, rpp, gpp, hp, g3p)
end
end
