module two_agentsSteadyState2
#
# NB: this file was automatically generated by Dynare
#     from two_agents.mod
#
export steady_state!

function steady_state!(ys_::Vector{<: Real}, exo_::Vector{<: Real}, params::Vector{<: Real})
@inbounds begin
    ys_[1]=params[9];
    ys_[2]=params[8];
    ys_[3]=params[11];
    ys_[4]=params[15];
    ys_[5]=params[10];
    ys_[6]=1/params[2];
    # Auxiliary equations
end
end
end
